import type { TemplateManifest } from './types';

export const LEDGER_MANIFEST: TemplateManifest = {
  id: 'ledger',
  editableSlots: [
    {
      id: 'page-title',
      label: '页面标题',
      category: 'content',
      type: 'text',
      defaultValue: '💰 极简记账',
      aiPrompt: '页面主标题，显示在顶部 h1 元素上。请在此元素上加 data-vibecraft-slot="page-title"',
    },
    {
      id: 'balance-card-style',
      label: '余额卡片风格',
      category: 'style',
      type: 'select',
      defaultValue: 'gradient',
      options: [
        { label: '渐变色', value: 'gradient' },
        { label: '纯色', value: 'solid' },
        { label: '极简边框', value: 'bordered' },
      ],
      aiPrompt: '顶部余额卡片的视觉风格。请在选择器对应的容器上加 data-vibecraft-slot="balance-card-style"',
    },
    {
      id: 'accent-color',
      label: '主题色',
      category: 'style',
      type: 'select',
      defaultValue: 'indigo',
      options: [
        { label: '靛蓝', value: 'indigo' },
        { label: '琥珀', value: 'amber' },
        { label: '翠绿', value: 'emerald' },
        { label: '玫红', value: 'rose' },
        { label: '紫色', value: 'violet' },
      ],
      aiPrompt: '应用主色调（按钮、选中态、强调色）。请将主色调对应的 CSS class 所在容器上加 data-vibecraft-slot="accent-color"',
    },
    {
      id: 'border-radius',
      label: '圆角大小',
      category: 'style',
      type: 'select',
      defaultValue: 'rounded-2xl',
      options: [
        { label: '0px（直角）', value: 'rounded-none' },
        { label: '8px', value: 'rounded-lg' },
        { label: '12px', value: 'rounded-xl' },
        { label: '16px', value: 'rounded-2xl' },
        { label: '24px', value: 'rounded-3xl' },
      ],
      aiPrompt: '卡片和容器的圆角大小，影响所有圆角元素。请在典型的圆角容器上加 data-vibecraft-slot="border-radius"',
    },
    {
      id: 'density',
      label: '布局密度',
      category: 'style',
      type: 'select',
      defaultValue: 'normal',
      options: [
        { label: '紧凑', value: 'compact' },
        { label: '适中', value: 'normal' },
        { label: '宽松', value: 'spacious' },
      ],
      aiPrompt: '列表项的间距和 padding。紧凑=更小间距，宽松=更大间距。请在列表容器上加 data-vibecraft-slot="density"',
    },
    {
      id: 'record-list',
      label: '记录列表',
      category: 'structure',
      type: 'block',
      aiPrompt: '收支记录列表区域。每条记录包含金额、分类、日期、备注和删除按钮。请在此区域容器上加 data-vibecraft-slot="record-list"',
    },
    {
      id: 'filter-bar',
      label: '筛选栏',
      category: 'structure',
      type: 'block',
      aiPrompt: '全部/支出/收入 筛选按钮组。请在此区域容器上加 data-vibecraft-slot="filter-bar"',
    },
    {
      id: 'add-form',
      label: '新增记录表单',
      category: 'structure',
      type: 'block',
      aiPrompt: '新增收支记录的表单，包含类型切换、金额输入、分类选择、备注和提交按钮。请在此区域容器上加 data-vibecraft-slot="add-form"',
    },
    {
      id: 'categories',
      label: '分类列表',
      category: 'data',
      type: 'text',
      defaultValue: '餐饮,交通,购物,娱乐,居住,医疗,教育,其他',
      aiPrompt: '收支分类选项列表，用逗号分隔。当前分类显示在 select 下拉和分类标签中。请在分类选择器上加 data-vibecraft-slot="categories"',
    },
    {
      id: 'summary-stat',
      label: '统计摘要文字',
      category: 'content',
      type: 'text',
      defaultValue: '本月余额',
      aiPrompt: '余额卡片中统计摘要的标签文字。请在此元素上加 data-vibecraft-slot="summary-stat"',
    },
    {
      id: 'theme-mode',
      label: '深色/浅色模式',
      category: 'style',
      type: 'select',
      defaultValue: 'dark',
      options: [
        { label: '深色', value: 'dark' },
        { label: '浅色', value: 'light' },
      ],
      aiPrompt: '整体深色或浅色配色方案。请在 body 或根容器上加 data-vibecraft-slot="theme-mode"',
    },
  ],
  dataSchema: [
    {
      name: 'records',
      type: 'array',
      label: '收支记录',
      description: '所有收支记录列表',
      fields: [
        { name: 'id', type: 'number', label: '记录 ID' },
        { name: 'type', type: 'string', label: '类型', description: 'income 或 expense' },
        { name: 'amount', type: 'number', label: '金额' },
        { name: 'category', type: 'string', label: '分类' },
        { name: 'note', type: 'string', label: '备注' },
        { name: 'date', type: 'string', label: '日期', description: 'YYYY-MM-DD 格式' },
      ],
    },
    {
      name: 'CATEGORIES',
      type: 'array',
      label: '分类列表',
      description: '字符串数组，如 ["餐饮", "交通", ...]',
    },
    {
      name: 'CATEGORY_COLORS',
      type: 'object',
      label: '分类颜色映射',
      description: '如 { "餐饮": "#f97316", ... }',
    },
  ],
  supportedSkills: ['chart', 'export_excel', 'budget_alert'],
  defaultSuggestions: [
    { text: '加一个饼图，按分类展示支出占比', skillId: 'chart', category: 'skill', condition: { type: 'skill_not_active', skillId: 'chart' } },
    { text: '加一个月度趋势折线图', skillId: 'chart', category: 'skill', condition: { type: 'skill_not_active', skillId: 'chart' } },
    { text: '增加导出 Excel 功能', skillId: 'export_excel', category: 'skill', condition: { type: 'skill_not_active', skillId: 'export_excel' } },
    { text: '设置预算，超支时提醒我', skillId: 'budget_alert', category: 'skill', condition: { type: 'skill_not_active', skillId: 'budget_alert' } },
    { text: '把标题改成更符合我的风格的', category: 'content' },
    { text: '让页面更适合在手机上查看', category: 'design' },
  ],
};
