import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { db } from '@/lib/db';
import JSZip from 'jszip';

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: '请先登录' }, { status: 401 });
  }

  const { projectId } = await req.json();

  const { data: project } = await db
    .from('projects')
    .select('current_html, name')
    .eq('id', projectId)
    .eq('user_id', session.user.id)
    .single();

  if (!project) {
    return NextResponse.json({ error: '项目不存在' }, { status: 404 });
  }

  const zip = new JSZip();
  zip.file('index.html', project.current_html);
  zip.file('README.txt', `${project.name}\n\nGenerated by VibeCraft\nOpen index.html in any browser to use.`);

  const content = await zip.generateAsync({ type: 'uint8array' });

  return new NextResponse(Buffer.from(content), {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${encodeURIComponent(project.name)}.zip"`,
    },
  });
}
