import type { TemplateMeta } from './types';

export const TEMPLATE_CATALOG: TemplateMeta[] = [
  {
    id: 'ledger',
    name: '极简记账本',
    description: '收支记录、分类统计，轻松管理财务',
    category: '工具',
    icon: '💰',
    cover_url: '/templates/local/ledger/cover.png',
    tags: ['记账', '财务', '统计'],
    compatibleSkills: ['chart', 'export_excel', 'budget_alert'],
    origin: { type: 'builtin' },
  },
  {
    id: 'todo',
    name: 'Todo 提醒',
    description: '任务管理、到期提醒，高效完成待办',
    category: '工具',
    icon: '✅',
    cover_url: '/templates/local/todo/cover.png',
    tags: ['待办', '任务', '提醒'],
    compatibleSkills: ['export_excel'],
    origin: { type: 'builtin' },
  },
  {
    id: 'checkin',
    name: '打卡手账',
    description: '每日习惯打卡、连续天数统计',
    category: '工具',
    icon: '📅',
    cover_url: '/templates/local/checkin/cover.png',
    tags: ['打卡', '习惯', '日历'],
    compatibleSkills: ['chart', 'export_excel'],
    origin: { type: 'builtin' },
  },
  {
    id: 'personal-portfolio',
    name: '个人作品集',
    description: '展示个人介绍、项目和联系方式的专业主页',
    category: '展示页',
    icon: '✦',
    cover_url: '/templates/local/personal-portfolio/cover.png',
    tags: ['作品集', '个人主页', '展示'],
    compatibleSkills: [],
    origin: {
      type: 'open-source',
      repo: 'https://github.com/tailwindlabs/tailwindcss-showcase',
      license: 'MIT',
      author: 'Tailwind Labs',
    },
  },
  {
    id: 'product-landing',
    name: '产品落地页',
    description: 'SaaS 产品 landing page，含特性展示和 CTA',
    category: '展示页',
    icon: '🚀',
    cover_url: '/templates/local/product-landing/cover.png',
    tags: ['落地页', '产品', '营销'],
    compatibleSkills: [],
    origin: {
      type: 'open-source',
      repo: 'https://github.com/tailwindlabs/tailwindcss-showcase',
      license: 'MIT',
      author: 'Tailwind Labs',
    },
  },
  {
    id: 'restaurant-menu',
    name: '小店菜单',
    description: '餐厅/咖啡店在线菜单，分类展示菜品与价格',
    category: '展示页',
    icon: '🍽️',
    cover_url: '/templates/local/restaurant-menu/cover.png',
    tags: ['菜单', '餐厅', '美食'],
    compatibleSkills: [],
    origin: {
      type: 'open-source',
      repo: 'https://github.com/tailwindlabs/tailwindcss-showcase',
      license: 'MIT',
      author: 'Tailwind Labs',
    },
  },
  {
    id: 'reading-notes',
    name: '读书笔记',
    description: '管理阅读书单和笔记，localStorage 持久化',
    category: '工具',
    icon: '📚',
    cover_url: '/templates/local/reading-notes/cover.png',
    tags: ['阅读', '笔记', '书单'],
    compatibleSkills: [],
    origin: {
      type: 'open-source',
      repo: 'https://github.com/tailwindlabs/tailwindcss-showcase',
      license: 'MIT',
      author: 'Tailwind Labs',
    },
  },
  {
    id: 'resume-page',
    name: '简历页面',
    description: '简洁专业在线简历，含技能、经历和教育背景',
    category: '展示页',
    icon: '📄',
    cover_url: '/templates/local/resume-page/cover.png',
    tags: ['简历', '求职', '个人'],
    compatibleSkills: [],
    origin: {
      type: 'open-source',
      repo: 'https://github.com/tailwindlabs/tailwindcss-showcase',
      license: 'MIT',
      author: 'Tailwind Labs',
    },
  },
  {
    id: 'content-calendar',
    name: '内容日历',
    description: '社交媒体内容规划日历，拖拽管理发布计划',
    category: '工具',
    icon: '📅',
    cover_url: '/templates/local/content-calendar/cover.png',
    tags: ['日历', '规划', '内容'],
    compatibleSkills: [],
    origin: {
      type: 'open-source',
      repo: 'https://github.com/tailwindlabs/tailwindcss-showcase',
      license: 'MIT',
      author: 'Tailwind Labs',
    },
  },
  {
    id: 'blank',
    name: '空白应用',
    description: '从一句话开始，让 AI 继续塑形的小应用起点',
    category: '起步',
    icon: '+',
    cover_url: '',
    tags: ['空白', '自定义'],
    compatibleSkills: [],
    origin: { type: 'builtin' },
  },
];
